### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by aerugo** [theborderland/realities#17]
Choose authentication solution and implement in backend.

**Comment by erikfrisk** [comment]
I propose Auth0. We should be able to stay of the free tier for a very long time, if not forever. I'm open to alternatives if anyone has a preference though.

**Comment by aerugo** [comment]
I'm pro using Auth0. Considering that we have an extensive todo list, getting a lot of functionality with little coding through Auth0 is very appealing right now.

**Comment by eminx** [comment]
Hey guys. I wrote the other issue also (sorry for the dup), wonder if we can implement SSO - so that we can enable crossing in between with the dreams platform easily? 

https://auth0.com/learn/how-to-implement-single-sign-on/

That'd be awesome.

**Comment by aerugo** [comment]
It would be cool, but might not be very straight forward to implement on
Dreams. Auth on Dreams is done with the Devise gem, which is also
responsible for access control in the front-end, and we also use some
custom scripts to verify against a list from the membership profile system
weather a user has a membership or not. I’m currently focusing on
Realities, so I don’t think I’ll have time to do a lot of work on Dreams
this year, but if somebody wants to have a crack at it just fork Dreams in
the Borderland repo and have a go!

**Comment by erikfrisk** [comment]
Using Auth0 should make it easier to implement SSO at some point in the future.

**Comment by erikfrisk** [comment]
Stuff I'm doing: 

- [x] Create Auth0 account
- [x] Configure API, client and Connections in Auth0 account
- [x] Create rule in Auth0 that adds a flag to the access_token with whether the user is an admin or not
- [x] Decode JWT in backend if passed in the Authentication header and add user info to the graphql context
- [x] Add auth service in frontend that facilitates logging in and out, storing tokens in localStorage
- [ ] Create a React HOC that tells other components whether the user is logged in, and if they're an admin
- [ ] Make Login/Signup/Logout in navbar look all pretty and stuff
- [ ] Redirect to page you were previously at after login
- [ ] Add user to our own database when a user signs up
- [ ] Create an example of how to secure a mutation in the backend (there is already a separate issue for this)
- [ ] Show banner in frontend after you sign up that prompts you to go fill out your profile with more info (name, phone number, etc.) (probably a separate issue)
- [ ] Handle case when auth token expires while you're in the app (will probably create a separate issue)
- [ ] Enable signing up with Facebook (will probably create a separate issue)

**Comment by erikfrisk** [comment]
Mostly done. Some remaining tasks have been logged in separate issues: #46, #47, #48, #49.
