### ISSUE TITLE
Delete button for need/responsibility, which calls "soft delete"

### ISSUE THREAD

**Issue by aerugo** [theborderland/realities#22]
User should be able to delete a responsibility according to these rules:

Delete responsibility: If user is Reality Guide for Responsibility OR if Reality Admin
Delete need: If Need has no FULFILS relations to Responsibilities and user is Reality Guide for Need OR if Reality Admin

Delete calls the removeResponsibilityMutation which calls a "soft delete" changing giving the node an is_deleted property and setting it to current timestamp().
Resolver cypher query defined in test/cypher-resolvers.cypher.

**Comment by erikfrisk** [comment]
Done, but without all authorization rules. See [issue 18](https://github.com/theborderland/realities/issues/18) for that.
