### ISSUE TITLE
Mutations for need/responsibilities dependencies

### ISSUE THREAD

**Issue by aerugo** [theborderland/realities#31]
createDependencyMutation: creates DEPENDS_ON directed towards another Need or Responsibility
Authentication: guide or realiser of need/responsibility or admin.

removeDependencyMutation: removes a DEPENDS_ON directed towards another Need or Responsibility
Authentication: guide or realiser of need/responsibility or admin.

Cypher queries for resolvers: #14

**Comment by erikfrisk** [comment]
Done, but without all authorization rules. See [issue 18](https://github.com/theborderland/realities/issues/18) for that.
