### ISSUE TITLE
Mutations to create/remove need and responsibility

### ISSUE THREAD

**Issue by aerugo** [theborderland/realities#32]
- [x] createNeedMutation: creates a Need with title as input parameter, and should set user to Reality Guide and Realizer
Authentication: Any user
- [x] createResponsibilityMutation: takes Need nodeId and title as input parameters and creates Responsibility with FULFILS to Need. Should set user to Reality Guide.
Authentication: Any user
- [x] removeResponsibilityMutation: SET Responsibility is_deleted to current timestamp()
Authentication: If user is Reality Guide for Responsibility OR if Reality Admin
- [x] removeNeedMutation: SET is_deleted to current timestamp() if Need has no FULFILS relations to Responsibilities
Authentication: If user is Reality Guide for Responsibility OR if Reality Admin

Cypher queries for resolvers: https://github.com/theborderland/realities/issues/14

**Comment by erikfrisk** [comment]
Done, but without all authorization rules. See [issue 18](https://github.com/theborderland/realities/issues/18) for that.
