### ISSUE TITLE
Move frontend source code into a src/ directory

### ISSUE THREAD

**Issue by erikfrisk** [theborderland/realities#4]
It's common to keep source code in a src/ directory in the root of the project, and build artifacts in a build/ directory (or some other name that makes sense). Next.js seems to force you to keep source code (at least the pages/ directory) in the root of the project. We should configure Next.js to allow for a separate src/ and build/ directory so that we can keep different things separate in the root folder going forward (source code, build artifacts, tests, deployment scripts, configuration, etc.).

**Comment by erikfrisk** [comment]
@gustavlrsn Do you know how to do this with Next.js. I spent some time on it last night but couldn't figure it out. It's driving me a little crazy :)

**Comment by lowlandjuju** [comment]
I will have a go at this

**Comment by erikfrisk** [comment]
Done since the move to create-react-app.
